### ISSUE TITLE
Use id instead of name in the label

### ISSUE THREAD

**Issue by meirkl** [shoaibkhan94/reactstrap-formik#5]
### Current Behavior
In the label, the `for` attribute points to the input name. In result the click on the label doesn’t trigger the the input focus.

### Expected behavior
The `for` attribute should point to the input id

To associate the `<label>` with an `<input>` element, you need to give the <input> an id attribute. The `<label>` then needs a `for` attribute whose value is the same as the input's `id`.

Alternatively, you can nest the `<input>` directly inside the `<label>`, in which case the `for` and `id` attributes are not needed because the association is implicit:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

![image](https://user-images.githubusercontent.com/19801904/53344464-68ffb700-391b-11e9-9b8a-6c1ff67d2e41.png)
https://www.w3schools.com/tags/tag_label.asp

### Suggested solution(s)
Change this

```
React.createElement(
            Label,
            { "for": field.name, className: "label-color" },
            props.label
        ),
```
to

```
React.createElement(
            Label,
            { "for": props.id, className: "label-color" },
            props.label
        ),
```

**Comment by shoaibkhan94** [comment]
Thanks for pointing it out. Fixed with version 1.0.8.
