### ISSUE TITLE
pass onChange and onBlur parameters

### ISSUE THREAD

**Issue by Ridder90** [shoaibkhan94/reactstrap-formik#6]
Thanks for this lib! 

I have this field which should trigger an onChange event. Unfortunatly it doesn't work with the `component={ReactstrapInput}` part included. Is there something wrong with my approach? 

``` 
 <Field
                     type="text"
                     placeholder="Certificaat"
                     name="certificate_id"
                     id="certificate_id"
                     component={ReactstrapInput}
                     onChange={ e => { alert('Change'); }}
                   />
```

**Comment by shoaibkhan94** [comment]
You don't need to write an onChange() event handler. The module handles change events for you.

**Comment by kfrajtak** [comment]
What if I want to update one field based on a value of different field?
