### ISSUE TITLE
Is there a way to omit the label?

### ISSUE THREAD

**Issue by Ridder90** [shoaibkhan94/reactstrap-formik#7]
Is it possible to pass a prop to hide the label?

Thanks again!

**Comment by shoaibkhan94** [comment]
Hi,
If you want to omit the label then just don't pass it as a prop to the Field.
E.g. -
`<Field
                  type="email"
                  placeholder="Email"
                  name="email"
                  id="email"
                  component={ReactstrapInput}
                />`
