### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by selique** [shoaibkhan94/reactstrap-formik#9]
×
SyntaxError: Unexpected identifier
(anonymous function)
C:\Users\Moshe\Desktop\projetos\sb-website\node_modules\reactstrap-formik\dist\index.js:1
new Script
vm.js:85:7
createScript
vm.js:266:10
runInThisContext
vm.js:314:10
Module._compile
internal/modules/cjs/loader.js:698:28
Module._extensions..js
internal/modules/cjs/loader.js:749:10
Module.load
internal/modules/cjs/loader.js:630:32
tryModuleLoad
internal/modules/cjs/loader.js:570:12
Function.Module._load
internal/modules/cjs/loader.js:562:3
Module.require
internal/modules/cjs/loader.js:667:17
require
internal/modules/cjs/helpers.js:20:18
reactstrap-formik
webpack:/external "reactstrap-formik":1
> 1 | module.exports = require("reactstrap-formik");
View compiled
__webpack_require__
./webpack/bootstrap:21
  18 | // Execute the module function
  19 | var threw = true;
  20 | try {
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
     | ^  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];
View compiled
Module../components/form-ouvidoria.js
/_next/development/server/static/development/pages/ouvidoria.js:499:75
__webpack_require__
./webpack/bootstrap:21
  18 | // Execute the module function
  19 | var threw = true;
  20 | try {
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
     | ^  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];
View compiled
Module../pages/ouvidoria.js
/_next/development/server/static/development/pages/ouvidoria.js:2501:87
__webpack_require__
./webpack/bootstrap:21
  18 | // Execute the module function
  19 | var threw = true;
  20 | try {
> 21 | 	modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
     | ^  22 | 	threw = false;
  23 | } finally {
  24 | 	if(threw) delete installedModules[moduleId];
View compiled
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

**Comment by coderdix** [comment]
Did you ever find a solution to this?
